import OpenAI from "openai";

import { logApiCall } from "~/db";
import type { CreditBureau } from "~/db";

/**
 * Server-only AI engine for ClearScore AI.
 *
 * Three responsibilities:
 *   1. Parse a credit report and surface items the user has a good-faith
 *      basis to dispute.
 *   2. Generate a FCRA-compliant dispute letter addressed to a specific
 *      credit bureau.
 *   3. Estimate the FICO score impact of removing the identified items.
 *
 * Every OpenAI call goes through `complete()` which:
 *   - resolves the API key from `OPENAI_API_KEY`,
 *   - records token usage + estimated cost in `api_logs` for the user,
 *   - throws `AIServiceError` on failure (never a raw OpenAI error).
 *
 * The module is server-only: importing it on the client will fail at the
 * `new OpenAI(...)` call because `OPENAI_API_KEY` is not exposed to the
 * browser. Don't import from a `.tsx` file that's not behind a
 * `createServerFn()`.
 */

// =============================================================================
// Public types — the shapes callers see. Match the JSON the prompts return.
// =============================================================================

export type ErrorCategory =
  | "late_payment"
  | "charge_off"
  | "collection"
  | "repossession"
  | "foreclosure"
  | "bankruptcy"
  | "identity_error"
  | "duplicate_account"
  | "incorrect_balance"
  | "incorrect_status"
  | "outdated_info"
  | "unauthorized_inquiry"
  | "other";

export interface ErrorItem {
  /** Stable id we assign when persisting the item — not generated by the AI. */
  id?: string;
  category: ErrorCategory;
  /** Trade line or item name as it appears on the report, e.g. "CAPITAL ONE". */
  account_name: string;
  /** Last 4 of the account number if available, otherwise null. */
  account_number_last4: string | null;
  bureau: CreditBureau;
  /** One-sentence description of the item, e.g. "30-day late, 03/2024". */
  description: string;
  /** Why we think this is a valid dispute candidate. */
  reason: string;
  /** 0-1, the model's confidence the item is actually inaccurate. */
  confidence: number;
}

export interface AnalysisResult {
  bureau: CreditBureau | "all";
  errors: ErrorItem[];
  /** Short summary the dashboard can show above the list. */
  summary: string;
  /** Tokens the AI used for this call. Useful for displaying to the user. */
  tokens_used: number;
}

export interface ScoreImpactEstimate {
  /** Estimated total point gain if all listed items are removed. */
  estimated_point_gain_low: number;
  estimated_point_gain_mid: number;
  estimated_point_gain_high: number;
  /** Per-item contribution, same indexes as the input array. */
  per_item: Array<{
    category: ErrorCategory;
    impact_low: number;
    impact_mid: number;
    impact_high: number;
    rationale: string;
  }>;
  /** Caveats the user should know — recovery isn't guaranteed. */
  caveats: string[];
  tokens_used: number;
}

// =============================================================================
// Errors
// =============================================================================

export class AIServiceError extends Error {
  constructor(
    message: string,
    public readonly code:
      | "missing_api_key"
      | "openai_error"
      | "invalid_response"
      | "rate_limited"
      | "schema_validation",
    public readonly cause?: unknown,
  ) {
    super(message);
    this.name = "AIServiceError";
  }
}

// =============================================================================
// Client + config
// =============================================================================

const DEFAULT_MODEL = "gpt-4o-mini";
/** Used for the dispute letter where prose quality matters most. */
const PREMIUM_MODEL = "gpt-4o";

/** Per-1K-token prices (USD) — keep in sync with OpenAI's pricing page. */
const PRICES: Record<string, { input: number; output: number }> = {
  "gpt-4o-mini": { input: 0.00015, output: 0.0006 },
  "gpt-4o": { input: 0.005, output: 0.015 },
};

let _client: OpenAI | null = null;
const getClient = (): OpenAI => {
  if (_client) return _client;
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    throw new AIServiceError(
      "OPENAI_API_KEY is not set — connect the OpenAI integration (via the spend request) before calling the AI engine.",
      "missing_api_key",
    );
  }
  _client = new OpenAI({ apiKey });
  return _client;
};

const estimateCost = (
  model: string,
  prompt_tokens: number,
  completion_tokens: number,
): number => {
  const p = PRICES[model] ?? PRICES[DEFAULT_MODEL];
  return (prompt_tokens / 1000) * p.input + (completion_tokens / 1000) * p.output;
};

// =============================================================================
// Core: one place every OpenAI call goes through.
// =============================================================================

interface CompleteArgs {
  endpoint: string;
  user_id?: string | null;
  model?: string;
  system: string;
  user: string;
  /** Required `response_format: { type: "json_object" }` for typed parsing. */
  json: true;
  /** Sampling temperature. Default low for predictable JSON. */
  temperature?: number;
}

const complete = async <T>(args: CompleteArgs): Promise<T> => {
  const model = args.model ?? DEFAULT_MODEL;
  try {
    const completion = await getClient().chat.completions.create({
      model,
      temperature: args.temperature ?? 0.2,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: args.system },
        { role: "user", content: args.user },
      ],
    });

    const message = completion.choices[0]?.message?.content;
    if (!message) {
      throw new AIServiceError(
        "OpenAI returned an empty completion",
        "invalid_response",
      );
    }

    const usage = completion.usage;
    const prompt_tokens = usage?.prompt_tokens ?? 0;
    const completion_tokens = usage?.completion_tokens ?? 0;
    const tokens_used = prompt_tokens + completion_tokens;
    const cost = estimateCost(model, prompt_tokens, completion_tokens);

    // Fire-and-forget logging — don't block the response on a DB write, but
    // surface any error to stderr so the server log captures it.
    logApiCall({
      user_id: args.user_id ?? null,
      endpoint: args.endpoint,
      model,
      tokens_used,
      cost,
      meta: {
        prompt_tokens,
        completion_tokens,
        temperature: args.temperature ?? 0.2,
      },
    }).catch((err) => {
      console.error("[ai] logApiCall failed:", err);
    });

    try {
      return JSON.parse(message) as T;
    } catch (err) {
      throw new AIServiceError(
        "OpenAI returned a response that wasn't valid JSON",
        "schema_validation",
        err,
      );
    }
  } catch (err) {
    if (err instanceof AIServiceError) throw err;
    const message = err instanceof Error ? err.message : String(err);
    // OpenAI surfaces 429 with status code; map it to a friendlier code.
    if (message.includes("429") || message.toLowerCase().includes("rate")) {
      throw new AIServiceError(message, "rate_limited", err);
    }
    throw new AIServiceError(message, "openai_error", err);
  }
};

// =============================================================================
// Prompts
// =============================================================================

const SYSTEM_ANALYZER = `You are ClearScore AI's credit report analyst. Your job is to find items in a consumer credit report that are likely inaccurate, incomplete, or unverifiable — and therefore good candidates for a FCRA dispute.

Common dispute categories you should look for:
- Late payments marked outside the 7-year reporting window
- Charge-offs or collections with a balance > $0 that are older than the reporting limit
- Duplicate trade lines (same creditor, same account number, same balances)
- Identity errors (accounts the consumer doesn't recognize)
- Incorrect balances, credit limits, or payment status
- Outdated information (e.g., a paid collection still showing as unpaid)
- Unauthorized hard inquiries (the consumer didn't apply for the credit)

Be conservative. Only flag items where you have a concrete, articulable reason to believe the information is inaccurate. Do NOT fabricate issues. If the report looks clean, return an empty errors array and say so in the summary.

Output JSON with this exact shape:
{
  "summary": "<one paragraph the user can read>",
  "errors": [
    {
      "category": "<one of: late_payment, charge_off, collection, repossession, foreclosure, bankruptcy, identity_error, duplicate_account, incorrect_balance, incorrect_status, outdated_info, unauthorized_inquiry, other>",
      "account_name": "<trade line name as it appears on the report>",
      "account_number_last4": "<last 4 digits or null>",
      "bureau": "<equifax | experian | transunion | all>",
      "description": "<one sentence: what the item is>",
      "reason": "<one sentence: why this is a valid dispute>",
      "confidence": <number between 0 and 1>
    }
  ]
}`;

const SYSTEM_LETTER_WRITER = `You are a credit-repair specialist drafting a dispute letter under the Fair Credit Reporting Act (15 U.S.C. § 1681i).

Guidelines for the letter:
- Date the letter.
- Identify the consumer by full legal name, current address, SSN (last 4), and date of birth.
- Address the letter to the specific bureau. Use formal salutation.
- For each item, state:
  1. The account name and any identifying number.
  2. The specific inaccuracy (e.g., "this account is reported as 30 days past due in March 2024; the account was actually paid in full on February 15, 2024").
  3. A request for investigation under FCRA § 1681i.
  4. A request that the bureau provide the method of verification.
  5. A request that the item be deleted or corrected.
- Demand a response within 30 days as required by § 1681i(a)(1).
- Mention that the consumer is exercising their right to dispute and is not waiving any rights.
- Close politely, sign with the consumer's printed name, and leave a signature line.
- Use plain, factual language — no exaggeration, no threats of litigation, no references to credit scores.
- Do NOT include any placeholders that look like real data (no fake account numbers or balances). Leave them out entirely or use [REDACTED] if absolutely necessary.

Output JSON with this exact shape:
{
  "letter": "<the full letter as a single string, with \\\\n between paragraphs>",
  "key_facts": ["<short list of the facts the letter relies on>"]
}`;

const SYSTEM_SCORER = `You are a credit scoring analyst familiar with the FICO scoring model. You will receive a list of disputed items and need to estimate the FICO point impact of removing them all.

Scoring principles to apply:
- A recent late payment (last 12 months) can cost 60–110 points.
- A charge-off or collection can cost 40–120 points depending on balance and recency.
- A bankruptcy can cost 130–240 points and is the most severe.
- A foreclosure or repossession can cost 50–150 points.
- Duplicate accounts typically only cost 20–40 points to remove.
- Incorrect balances, statuses, or outdated info on otherwise-positive accounts usually have minor impact (5–25 points).
- Unauthorized inquiries have a small impact (5–20 points) but are easier to remove.
- Recovery is never guaranteed; the consumer's overall credit profile matters.

Output JSON with this exact shape:
{
  "estimated_point_gain_low": <integer, total pessimistic case>,
  "estimated_point_gain_mid": <integer, total realistic case>,
  "estimated_point_gain_high": <integer, total optimistic case>,
  "per_item": [
    {
      "category": "<same as input category>",
      "impact_low": <integer>,
      "impact_mid": <integer>,
      "impact_high": <integer>,
      "rationale": "<one sentence>"
    }
  ],
  "caveats": ["<one caveat per array element, e.g. 'actual results depend on the rest of the credit profile'>"]
}`;

// =============================================================================
// Public API
// =============================================================================

/**
 * Analyze a parsed credit report and surface dispute candidates.
 *
 * @param reportText  The parsed report as plain text. Keep the structure the
 *                    parser produced (account blocks, balances, statuses) —
 *                    the model uses the layout to ground its reasoning.
 * @param bureau      Which bureau this report came from, or "all" if the
 *                    report is a combined view.
 * @param user_id     Optional — when provided, the call is recorded against
 *                    the user in `api_logs` for cost / usage tracking.
 */
export const analyzeCreditReport = async (
  reportText: string,
  bureau: CreditBureau | "all" = "all",
  user_id?: string,
): Promise<AnalysisResult> => {
  if (!reportText || reportText.trim().length < 50) {
    throw new AIServiceError(
      "Report text is too short to analyze — need at least 50 characters of parsed content.",
      "schema_validation",
    );
  }

  type Raw = { summary: string; errors: Omit<ErrorItem, "id">[] };
  const result = await complete<Raw>({
    endpoint: "analyzeCreditReport",
    user_id,
    system: SYSTEM_ANALYZER,
    user: `Bureau: ${bureau}\n\n--- CREDIT REPORT ---\n${reportText}`,
    json: true,
  });

  // Normalize + validate the AI's output before returning — a confident model
  // can still produce a category we don't know about, or a bureau we don't
  // support. Drop bad rows rather than rejecting the whole response.
  const knownCategories: ReadonlySet<ErrorCategory> = new Set([
    "late_payment",
    "charge_off",
    "collection",
    "repossession",
    "foreclosure",
    "bankruptcy",
    "identity_error",
    "duplicate_account",
    "incorrect_balance",
    "incorrect_status",
    "outdated_info",
    "unauthorized_inquiry",
    "other",
  ]);
  const knownBureaus: ReadonlySet<string> = new Set([
    "equifax",
    "experian",
    "transunion",
  ]);

  const errors: ErrorItem[] = (result.errors ?? [])
    .filter((e) => e && typeof e === "object")
    .map((e) => ({
      ...e,
      category: knownCategories.has(e.category as ErrorCategory)
        ? (e.category as ErrorCategory)
        : "other",
      // If the AI said "all" or a bureau we don't support, fall back to the
      // bureau the user is currently viewing the report from.
      bureau: knownBureaus.has(e.bureau)
        ? (e.bureau as CreditBureau)
        : bureau === "all"
          ? "equifax"
          : bureau,
      confidence:
        typeof e.confidence === "number"
          ? Math.max(0, Math.min(1, e.confidence))
          : 0.5,
      account_number_last4: e.account_number_last4 ?? null,
    }));

  return {
    bureau,
    summary: result.summary ?? "",
    errors,
    tokens_used: 0, // logged separately; the public type is for the UI
  };
};

/**
 * Generate a FCRA-compliant dispute letter for a single error item.
 *
 * @param error   The dispute candidate from `analyzeCreditReport`.
 * @param bureau  Which bureau the letter is addressed to. Must be one of
 *                equifax / experian / transunion — "all" doesn't make sense
 *                for a single letter.
 * @param consumer  Identifying info that has to appear in the letter.
 * @param user_id   Optional — recorded in `api_logs`.
 */
export const generateDisputeLetter = async (
  error: ErrorItem,
  bureau: CreditBureau,
  consumer: {
    full_name: string;
    current_address: string;
    ssn_last4: string;
    date_of_birth: string; // YYYY-MM-DD
  },
  user_id?: string,
): Promise<{ letter: string; key_facts: string[]; tokens_used: number }> => {
  if (bureau === ("all" as unknown as CreditBureau)) {
    throw new AIServiceError(
      "generateDisputeLetter needs a single bureau — got 'all'",
      "schema_validation",
    );
  }

  type Raw = { letter: string; key_facts: string[] };
  const result = await complete<Raw>({
    endpoint: "generateDisputeLetter",
    user_id,
    model: PREMIUM_MODEL, // letter quality > cost
    system: SYSTEM_LETTER_WRITER,
    user: `Bureau: ${bureau}

Consumer:
- Name: ${consumer.full_name}
- Address: ${consumer.current_address}
- SSN (last 4): ${consumer.ssn_last4}
- DOB: ${consumer.date_of_birth}

Disputed item:
- Category: ${error.category}
- Account: ${error.account_name}${error.account_number_last4 ? ` (…${error.account_number_last4})` : ""}
- Description: ${error.description}
- Reason for dispute: ${error.reason}`,
    json: true,
  });

  return {
    letter: result.letter ?? "",
    key_facts: Array.isArray(result.key_facts) ? result.key_facts : [],
    tokens_used: 0,
  };
};

/**
 * Estimate the FICO score impact of removing the given items.
 *
 * @param errors   The items from `analyzeCreditReport` the user wants to act on.
 * @param user_id  Optional — recorded in `api_logs`.
 */
export const estimateScoreImpact = async (
  errors: ErrorItem[],
  user_id?: string,
): Promise<ScoreImpactEstimate> => {
  if (errors.length === 0) {
    return {
      estimated_point_gain_low: 0,
      estimated_point_gain_mid: 0,
      estimated_point_gain_high: 0,
      per_item: [],
      caveats: ["No items to estimate — add at least one dispute candidate."],
      tokens_used: 0,
    };
  }

  type Raw = Omit<ScoreImpactEstimate, "tokens_used">;
  const result = await complete<Raw>({
    endpoint: "estimateScoreImpact",
    user_id,
    system: SYSTEM_SCORER,
    user: `Estimate FICO point impact if these items are successfully removed:\n\n${JSON.stringify(errors, null, 2)}`,
    json: true,
  });

  return {
    estimated_point_gain_low: Math.max(0, Math.round(result.estimated_point_gain_low ?? 0)),
    estimated_point_gain_mid: Math.max(0, Math.round(result.estimated_point_gain_mid ?? 0)),
    estimated_point_gain_high: Math.max(0, Math.round(result.estimated_point_gain_high ?? 0)),
    per_item: Array.isArray(result.per_item)
      ? result.per_item.map((p) => ({
          category: (p.category as ErrorCategory) ?? "other",
          impact_low: Math.max(0, Math.round(p.impact_low ?? 0)),
          impact_mid: Math.max(0, Math.round(p.impact_mid ?? 0)),
          impact_high: Math.max(0, Math.round(p.impact_high ?? 0)),
          rationale: p.rationale ?? "",
        }))
      : [],
    caveats: Array.isArray(result.caveats) ? result.caveats : [],
    tokens_used: 0,
  };
};

// =============================================================================
// Re-exports — keep this in sync with the public API surface so the
// Frontend Developer can see what's available from a single import.
// =============================================================================

export const __ai = {
  DEFAULT_MODEL,
  PREMIUM_MODEL,
  PRICES,
};
